In [1]:
import tensorflow as tf

In [3]:
hello=tf.constant("Hello World")
print(hello)

tf.Tensor(b'Hello World', shape=(), dtype=string)


In [5]:
print(hello.numpy())

b'Hello World'


Basic tensor Operations


In [6]:
a=tf.constant(2)
b=tf.constant(3)
c=tf.constant(5)

In [8]:
#various tensor operations.
add=tf.add(a,b)
sub=tf.subtract(a,b)
multi=tf.multiply(a,b)
div=tf.divide(a,b)

In [12]:
print(add)
print("Add:",add.numpy())
print("Subtract:",sub.numpy())
print("Multiplication:",multi.numpy())
print("Division:",div.numpy())


tf.Tensor(5, shape=(), dtype=int32)
Add: 5
Subtract: -1
Multiplication: 6
Division: 0.6666666666666666


In [15]:
mean=tf.reduce_mean([a,b,c])
sum=tf.reduce_sum([a,b,c])
print("Mean: ",mean.numpy())
print("Sum: ",sum.numpy())

Mean:  3
Sum:  10


In [17]:
matrix1=tf.constant([[1,2],[3,4]])
matrix2=tf.constant([[5,6],[7,8]])
matrix_product=tf.matmul(matrix1,matrix2)

Matrix Product:  [[19 22]
 [43 50]]


In [18]:
matrix_product

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]], dtype=int32)>

In [20]:
print(matrix_product.numpy())

[[19 22]
 [43 50]]


In [21]:
print("Matrix Product: ",matrix_product.numpy())

Matrix Product:  [[19 22]
 [43 50]]


**Lab 1**

In [23]:
import tensorflow as tf
import numpy as np

In [24]:
#X: independent Variable (input)
#Y: Dependent Variable (target/output), defined as y=4* X +2
x=np.array([1,2,3,4,5],dtype=np.float32)
y=np.array([6,10,14,18,22],dtype=np.float32)

In [28]:
#Define the model
#A simple model with dense Layer and one unit, suitable for linear regression
model=tf.keras.Sequential([
                           tf.keras.layers.Dense(1, input_shape=(1,))])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [37]:
#compile the model
#using 'sgd' optimizer and mean_sqaured_error
model.compile(optimizer='sgd',loss='mean_squared_error')

In [39]:
#Train the model
#Fit the model to the data of 100 epochs
model.fit(x,y,epochs=100,verbose=0)  #verbose will hide the training part

In [40]:
#Predict
#using the model to predict for new input data
X_new=np.array([6,7,8],dtype=np.float32)
predictions=model.predict(X_new)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step


In [43]:
print("Predictions [6,7,8]:",predictions)
print("Predictions [6,7,8]:",predictions.squeeze())

Predictions [6,7,8]: [[26.112133]
 [30.159056]
 [34.205982]]
Predictions [6,7,8]: [26.112133 30.159056 34.205982]


**Lab 2**

In [53]:
import tensorflow as tf
import numpy as np

In [54]:
#Here we took 2 features
X1=np.array([1,2,3,4,5,6,7,8,9,10],dtype=np.float32)
X2=np.array([1,2,3,4,5,6,7,8,9,10],dtype=np.float32)

In [55]:
#Stack X1 and X2 to form a 2D array of Shape(5,2)
X=np.column_stack((X1,X2))

In [56]:
# Traget values (y) with some relationship with X1 and X2
y=3*X1+2*X2+1

In [57]:
model=tf.keras.Sequential([tf.keras.layers.Dense(1,input_shape=(2,))])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [58]:
model.compile(optimizer='sgd',loss='mean_squared_error')

In [59]:
model.fit(X,y,epochs=100,verbose=0)

In [60]:
X_new=np.array([[6,0],[7,-1],[8,-2]],dtype=np.float32)
predictions=model.predict(X_new)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 91ms/step


In [62]:
print("Predictions:",predictions.squeeze())

Predictions: [12.474282 11.384994 10.295705]


In [70]:
#Assignment
#y=2x-1
X=np.array([1,2,3,4,5,6,7,8],dtype=np.float32)
y=np.array([1,3,5,7,9,11,13,15],dtype=np.float32)

In [71]:
model=tf.keras.Sequential([tf.keras.layers.Dense(1,input_shape=(1,))])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [72]:
model.compile(optimizer='sgd',loss='mean_squared_error')

In [73]:
model.fit(X,y,epochs=100,verbose=0)

In [76]:
X_new=np.array([9,10,11],dtype=np.float32)
predictions=model.predict(X_new)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step


In [78]:
print(predictions.squeeze())

[16.569096 18.441523 20.31395 ]
